server:
  port: 8081
  name: mngr

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    schema: public
    username: postgres
    password: pg123
    schema-generate: CREATE_DROP

  test:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    schema: public
    username: postgres
    password: pg123
    schema-generate: CREATE_DROP

kafka:
  consumers:
    default:
      bootstrap:
        servers: localhost:29092
      auto:
        offset:
          reset: earliest
    test:
      bootstrap:
        servers: localhost:29092
      auto:
        offset:
          reset: earliest
  producers:
    default:
      retries: 3
      bootstrap:
        servers: localhost:29092
    test:
      retries: 3
      bootstrap:
        servers: localhost:29092
